# docker compose file for rails and postgres
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: bin/rails s -p 3000 -b 0.0.0.0
    entrypoint: ./entrypoint.sh
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432
    ports:
      - "3000:3000"
    volumes:
      - .:/app
volumes:
  postgres:
